#!/bin/bash
#About this script

clear
echo -e "                                                        "
echo -e "\e[94m   :::::::::  :::::::::: :::::::::  :::::::::::   "
echo -e "\e[94m   :+:    :+: :+:        :+:    :+: :+:     :+:   "
echo -e "\e[94m   +:+    +:+ +:+        +:+    +:+        +:+    "
echo -e "\e[94m   #+     +:+ +#++:++#   +#++:++#+        +#+     "
echo -e "\e[94m   +#+    +#+ +#+        +#+    +#+      +#+      "
echo -e "\e[94m   #+#    #+# #+#        #+#    #+#     #+#       "
echo -e "\e[94m   #########  ########## #########      ###       "
echo -e "\e[94m         Deb7AutoScriptVPS by _Dreyannz_          "
echo -e "                                                        "
echo -e "\e[94m##################################################"
echo -e "\e[94m#                                                #"
echo -e "\e[94m#          For Debian 7 32 bit & 64 bit          #"
echo -e "\e[94m#   For VPS with KVM and VMWare virtualization   #"
echo -e "\e[94m#                                                #"
echo -e "\e[94m#              Original Script by:               #"
echo -e "\e[94m#                    Fornesia                    #"
echo -e "\e[94m#                   Rzengineer                   #"
echo -e "\e[94m#                     Fawzya                     #"
echo -e "\e[94m#                                                #"
echo -e "\e[94m#                Improvements by:                #"
echo -e "\e[94m#                    Dreyannz                    #"
echo -e "\e[94m#                                                #"
echo -e "\e[94m##################################################"
echo -e "\e[0m                                                   "
echo -e "                                                        "
echo -e "                                                        "
