#!/bin/bash
#Menu

clear
echo -e ""
echo -e ":::::::::  :::::::::: :::::::::  :::::::::::"
echo -e ":+:    :+: :+:        :+:    :+: :+:     :+:"
echo -e "+:+    +:+ +:+        +:+    +:+        +:+ "
echo -e "+#+    +:+ +#++:++#   +#++:++#+        +#+  "
echo -e "+#+    +#+ +#+        +#+    +#+      +#+   "
echo -e "#+#    #+# #+#        #+#    #+#     #+#    "
echo -e "#########  ########## #########      ###    "
echo -e ""
echo -e "Deb7AutoScriptVPS by _Dreyannz_"
echo -e ""
echo -e ""
echo -e "* menu      : Show Commands"
echo -e "* add       : Create User Account"
echo -e "* trial     : Create Trial Account"
echo -e "* remove    : Remove User Accounts"
echo -e "* check     : Check User Login"
echo -e "* member    : Check Member"
echo -e "* restart   : restart Services such as:"
echo -e "              Dropbear, Webmin, Squid3"
echo -e "              SSH and OpenVPN"
echo -e "* reboot    : reboot VPS"
echo -e "* speedtest : speedtest VPS"
echo -e "* info      : System Information"
echo -e "* about     : Debian AutoScript VPS Info"
echo -e "* exit      : Close Putty / JuiceSSH"
echo -e ""
