#!/bin/bash
#Menu

clear
echo -e "                                                        "
echo -e "\e[94m   :::::::::  :::::::::: :::::::::  :::::::::::   "
echo -e "\e[94m   :+:    :+: :+:        :+:    :+: :+:     :+:   "
echo -e "\e[94m   +:+    +:+ +:+        +:+    +:+        +:+    "
echo -e "\e[94m   #+     +:+ +#++:++#   +#++:++#+        +#+     "
echo -e "\e[94m   +#+    +#+ +#+        +#+    +#+      +#+      "
echo -e "\e[94m   #+#    #+# #+#        #+#    #+#     #+#       "
echo -e "\e[94m   #########  ########## #########      ###       "
echo -e "\e[94m         Deb7AutoScriptVPS by _Dreyannz_          "
echo -e "\e[0m                                                   "
echo -e "                                                        "
echo -e "\e[94m##################################################"
echo -e "\e[94m#   Commands           Description               #"
echo -e "\e[94m#                                                #"
echo -e "\e[94m#   menu       ----    Show Commands             #"
echo -e "\e[94m#   add        ----    Create User Account       #"
echo -e "\e[94m#   trial      ----    Create Trial Account      #"
echo -e "\e[94m#   remove     ----    Remove Account            #"
echo -e "\e[94m#   check      ----    Check Account Login       #"
echo -e "\e[94m#   member     ----    Check Users               #"
echo -e "\e[94m#   banner     ----    Configure Server Message  #"
echo -e "\e[94m#   restart    ----    Restart Services          #"
echo -e "\e[94m#   reboot     ----    Reboot VPS                #"
echo -e "\e[94m#   speedtest  ----    Speedtest VPS             #"
echo -e "\e[94m#   info       ----    System Information        #"
echo -e "\e[94m#   about      ----    Deb7AutoScriptVPS Info    #"
echo -e "\e[94m#   exit       ----    Close Putty / JuiceSSH    #"
echo -e "\e[94m#                                                #"
echo -e "\e[94m##################################################"
echo -e "\e[0m                                                   "
echo -e "                                                        "
echo -e "                                                        "
