#!/bin/bash
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";
apt-get -y install squid3
wget -O /etc/squid3/squid.conf "https://pastebin.com/raw/LeahN3uG"
sed -i $MYIP2 /etc/squid3/squid.conf;
service squid3 restart
